# for debian based distributions

- name: Check filebeat deb existence
  local_action: stat path="../files/{{ filebeat.rhel.package_name }}"
  register: check_filebeat_deb_existence

# - name: copy local filebeat deb to remote if exists  
#   copy: src={{ item }} dest={{ work_dir }}
#   with_fileglob:
#     - "../files/filebeat*.deb"
#   when: check_filebeat_deb_existence

- name: copy local filebeat deb to remote if exists  
  copy: src=../files/{{ filebeat.deb.package_name }} dest={{ work_dir }}
  #when: check_filebeat_deb_existence.stat.exists
  register: check_filebeat_deb_existence

- name: Check filebeat DEB
  stat: 
    path : "{{ work_dir }}/{{ filebeat.deb.package_name }}"
  register: check_filebeat_installer_deb

- name: Download filebeat package DEB
  get_url:
    url: "{{ filebeat.deb.url }}"
    dest: "{{ work_dir }}"
    validate_certs: false
  become: true
  environment:
    http_proxy: "{{ proxy_env }}"
    https_proxy: "{{ proxy_env }}"
  changed_when: false
  when: not check_filebeat_installer_deb.stat.exists and
        not check_filebeat_deb_existence.stat.exists and
        (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')

- name: remove filebeat if exists
  apt: 
    name: filebeat
    state: absent
  become: true

- name: Install filebeat package DEB
  apt:
    deb: "{{ work_dir }}/{{ filebeat.deb.package_name }}"
    state: present
  become: true
